// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Games", testGames)
	t.Run("GooseDBVersions", testGooseDBVersions)
	t.Run("Publishers", testPublishers)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("Games", testGamesDelete)
	t.Run("GooseDBVersions", testGooseDBVersionsDelete)
	t.Run("Publishers", testPublishersDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Games", testGamesQueryDeleteAll)
	t.Run("GooseDBVersions", testGooseDBVersionsQueryDeleteAll)
	t.Run("Publishers", testPublishersQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Games", testGamesSliceDeleteAll)
	t.Run("GooseDBVersions", testGooseDBVersionsSliceDeleteAll)
	t.Run("Publishers", testPublishersSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Games", testGamesExists)
	t.Run("GooseDBVersions", testGooseDBVersionsExists)
	t.Run("Publishers", testPublishersExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("Games", testGamesFind)
	t.Run("GooseDBVersions", testGooseDBVersionsFind)
	t.Run("Publishers", testPublishersFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("Games", testGamesBind)
	t.Run("GooseDBVersions", testGooseDBVersionsBind)
	t.Run("Publishers", testPublishersBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("Games", testGamesOne)
	t.Run("GooseDBVersions", testGooseDBVersionsOne)
	t.Run("Publishers", testPublishersOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("Games", testGamesAll)
	t.Run("GooseDBVersions", testGooseDBVersionsAll)
	t.Run("Publishers", testPublishersAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("Games", testGamesCount)
	t.Run("GooseDBVersions", testGooseDBVersionsCount)
	t.Run("Publishers", testPublishersCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("Games", testGamesHooks)
	t.Run("GooseDBVersions", testGooseDBVersionsHooks)
	t.Run("Publishers", testPublishersHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Games", testGamesInsert)
	t.Run("Games", testGamesInsertWhitelist)
	t.Run("GooseDBVersions", testGooseDBVersionsInsert)
	t.Run("GooseDBVersions", testGooseDBVersionsInsertWhitelist)
	t.Run("Publishers", testPublishersInsert)
	t.Run("Publishers", testPublishersInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("GameToUserUsingOwnerUser", testGameToOneUserUsingOwnerUser)
	t.Run("GameToPublisherUsingPublisher", testGameToOnePublisherUsingPublisher)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("PublisherToGames", testPublisherToManyGames)
	t.Run("UserToOwnerUserGames", testUserToManyOwnerUserGames)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("GameToUserUsingOwnerUserGames", testGameToOneSetOpUserUsingOwnerUser)
	t.Run("GameToPublisherUsingGames", testGameToOneSetOpPublisherUsingPublisher)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("GameToUserUsingOwnerUserGames", testGameToOneRemoveOpUserUsingOwnerUser)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("PublisherToGames", testPublisherToManyAddOpGames)
	t.Run("UserToOwnerUserGames", testUserToManyAddOpOwnerUserGames)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("UserToOwnerUserGames", testUserToManySetOpOwnerUserGames)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("UserToOwnerUserGames", testUserToManyRemoveOpOwnerUserGames)
}

func TestReload(t *testing.T) {
	t.Run("Games", testGamesReload)
	t.Run("GooseDBVersions", testGooseDBVersionsReload)
	t.Run("Publishers", testPublishersReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Games", testGamesReloadAll)
	t.Run("GooseDBVersions", testGooseDBVersionsReloadAll)
	t.Run("Publishers", testPublishersReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Games", testGamesSelect)
	t.Run("GooseDBVersions", testGooseDBVersionsSelect)
	t.Run("Publishers", testPublishersSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Games", testGamesUpdate)
	t.Run("GooseDBVersions", testGooseDBVersionsUpdate)
	t.Run("Publishers", testPublishersUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Games", testGamesSliceUpdateAll)
	t.Run("GooseDBVersions", testGooseDBVersionsSliceUpdateAll)
	t.Run("Publishers", testPublishersSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
