// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Games          string
	GooseDBVersion string
	Publishers     string
	Users          string
}{
	Games:          "games",
	GooseDBVersion: "goose_db_version",
	Publishers:     "publishers",
	Users:          "users",
}
