openapi: 3.0.3
info:
  title: JFT
  description: JFT
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /nft:
    get:
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Nft'
      operationId: getNftByID


components:
  schemas:
    Nft:
      type: object
      properties:
        id:
          type: string
        name:
          type: string